add git packaging hooks for debian

diff --git a/post-commit b/post-commit
--- a/post-commit
+++ b/post-commit
@@ -18,24 +18,24 @@
 #  along with git-packaging-hooks.  If not, see <http://www.gnu.org/licenses/>.
 
 
-readonly HOOKS_DIR=$(git config --local core.hooksPath)
-readonly COMMON_DEFS_FILE=${HOOKS_DIR}/common.sh.inc
+readonly HOOKS_PATH=$(git config --local core.hooksPath)
+readonly COMMON_DEFS_FILE=$HOOKS_PATH/common.sh.inc
 source $COMMON_DEFS_FILE
-[ ! -f $COMMON_DEFS_FILE ] && Error "missing ${HOOKS_DIR}/common.sh.inc - aborting commit" && exit 1
+[ ! -f $COMMON_DEFS_FILE ] && TraceError "missing $COMMON_DEFS_FILE - aborting commit" && exit 1
 
 
-if (($IS_DEVELOPMENT_BRANCH))
-then TraceStage "running generic post-commit hooks"
+if (($IS_STAGING_BRANCH))
+then TraceStage "running staging-specific post-commit hooks"
 
      # set "release" tag
      for revision_tag in $REVISION_TAGS
      do  TraceStep "removing un-merged revision tag '$revision_tag'"
-         git tag --delete $revision_tag
+         git tag --delete $revision_tag > /dev/null
      done
      if   [ ! -f $TAGS_FILE ]
      then TraceStep "adding revision tag '$VERSION_STRING'"
           git tag $VERSION_STRING
-     else declare -a orphaned_tags=($(cat $TAGS_FILE | sort | uniq))
+     else declare -a orphaned_tags=( $(cat $TAGS_FILE | sort | uniq) )
           orphaned_minor_tag=${orphaned_tags[0]}
           orphaned_rev_tag=${orphaned_tags[1]}
           orphaned_other_tags=${orphaned_tags[@]:2}
@@ -46,9 +46,20 @@ then TraceStage "running generic post-commit hooks"
           rm $TAGS_FILE
      fi
 
-     # re-configure autotools, commit automated changes, and ensure signed
+     # re-configure autotools, rebuild, install, and verify
      TraceStep "re-configuring autotools"
+     sudo make uninstall          2&> /dev/null
+     make distclean               2&> /dev/null
      autoreconf --force --install
+     TraceStep "verifying re-build/install"
+     ./configure                  2&> /dev/null
+     make -j$N_MAKE_JOBS          2&> /dev/null
+     sudo make install            2&> /dev/null
+     make installcheck            2&> /dev/null
+     sudo make uninstall          2&> /dev/null
+     make distclean               2&> /dev/null
+
+     # commit automated changes, and ensure signed
      git add --all
      git diff --exit-code --cached > /dev/null && is_index_clean=1        || is_index_clean=0
      git verify-commit --raw HEAD 2> /dev/null && has_trusted_signature=1 || has_trusted_signature=0
@@ -56,6 +67,8 @@ then TraceStage "running generic post-commit hooks"
      (($has_trusted_signature)) || TraceStep "amending commit to ensure signature exists"
      (($is_index_clean)) && (($has_trusted_signature))              || \
      git commit --gpg-sign --amend --reuse-message=HEAD > /dev/null
+
+     TraceStage "completed staging-specific post-commit hooks"
 elif (($IS_PACKAGING_BRANCH))
 then (($IS_AMEND_COMMIT)) && exit 0
 
@@ -63,7 +76,7 @@ then (($IS_AMEND_COMMIT)) && exit 0
 
      # implode tarball
      TraceStep "imploding tarball"
-     rm $OBS_DIR/*.tar.gz $OBS_DIR/*.sig 2> /dev/null
+     rm $TARBALL_FILE $TARBALL_FILE.sig $PKGBUILD_FILE.sig 2> /dev/null
      git archive --prefix=$TARBALL_INNER_DIR/ --output=$TARBALL_FILE $VERSION_STRING
 
      # generate tarball metadata
@@ -72,21 +85,24 @@ then (($IS_AMEND_COMMIT)) && exit 0
      TARBALL_SHA1SUM="$(  sha1sum    $TARBALL_FILE | cut --delimiter=' ' --fields=1)                        "
      TARBALL_SHA256SUM="$(sha256sum  $TARBALL_FILE | cut --delimiter=' ' --fields=1)"
      FILE_SIZE=$(         wc --bytes $TARBALL_FILE | cut --delimiter=' ' --fields=1)
-     PKGBUILD_MD5SUMS="'$KEYFILE_MD5SUM' '$TARBALL_MD5SUM' SKIP SKIP"
+#      PKGBUILD_MD5SUMS="'$TARBALL_MD5SUM' SKIP SKIP"
+     PKGBUILD_MD5SUMS="'$TARBALL_MD5SUM'"
 
      # inject tarball metadata into packaging files
-     TraceStep "processing packaging files"
-     echo "Checksums-Sha1:"                                         >> $DSC_FILE
-     echo " $TARBALL_SHA1SUM $FILE_SIZE $DEB_TARBALL_FILENAME"      >> $DSC_FILE
-     echo "Checksums-Sha256:"                                       >> $DSC_FILE
-     echo " $TARBALL_SHA256SUM $FILE_SIZE $DEB_TARBALL_FILENAME"    >> $DSC_FILE
-     echo "Files:"                                                  >> $DSC_FILE
-     echo " $FAUX_DSC_MD5SUM $FAUX_DSC_SIZE $DEB_TARBALL_FILENAME"  >> $DSC_FILE
-     echo " $FAUX_DSC_MD5SUM $FAUX_DSC_SIZE $DEB_DIFFBALL_FILENAME" >> $DSC_FILE
-     sed --in-place "s/^md5sums=.*$/md5sums=($PKGBUILD_MD5SUMS)/"      $PKGBUILD_FILE
+     TraceStep "preparing packaging files"
+     for dsc_file in ${DSC_FILES[@]}
+     do  echo "Checksums-Sha1:"                                         >> $dsc_file
+         echo " $TARBALL_SHA1SUM $FILE_SIZE $DEB_TARBALL_FILENAME"      >> $dsc_file
+         echo "Checksums-Sha256:"                                       >> $dsc_file
+         echo " $TARBALL_SHA256SUM $FILE_SIZE $DEB_TARBALL_FILENAME"    >> $dsc_file
+         echo "Files:"                                                  >> $dsc_file
+         echo " $FAUX_DSC_MD5SUM $FAUX_DSC_SIZE $DEB_TARBALL_FILENAME"  >> $dsc_file
+         echo " $FAUX_DSC_MD5SUM $FAUX_DSC_SIZE $DEB_DIFFBALL_FILENAME" >> $dsc_file
+     done
+     sed --in-place "s/^md5sums=.*$/md5sums=( $PKGBUILD_MD5SUMS )/"        $PKGBUILD_FILE
 
      # set uniform commit message and ensure signed
-     git commit --gpg-sign --amend --message="$COMMIT_MSG" > /dev/null
+     git commit --gpg-sign --amend --allow-empty --message="$GIT_COMMIT_MSG" > /dev/null
 
      # sign tarball and PKGBUILD
      gpg --detach-sign --yes $TARBALL_FILE
@@ -96,8 +112,8 @@ then (($IS_AMEND_COMMIT)) && exit 0
      ### github steps ###
 
      # create upstream tarball
-     TraceStep "pushing packaging branch and tags to github"
-     git push --force --tags $REMOTE_NAME $DEVELOPMENT_BRANCH $PACKAGING_BRANCH 2> /dev/null
+     TraceStep "pushing staging branch, packaging branch, and revision tag to github"
+     git push --force $REMOTE_NAME $STAGING_BRANCH $PACKAGING_BRANCH $VERSION_STRING 2> /dev/null
 
      # destroy any existing github "tag release" with same tag
      TraceStep "querying existing github \"tag release\" '$VERSION_STRING'"
@@ -162,11 +178,11 @@ then (($IS_AMEND_COMMIT)) && exit 0
      TraceStep "downloading remote tarball, PKGBUILD, and signatures"
      curl $CURL_FETCH_ARGS $TARBALL_URL     ; curl $CURL_FETCH_ARGS $PKGBUILD_URL     ;
      curl $CURL_FETCH_ARGS $TARBALL_SIG_URL ; curl $CURL_FETCH_ARGS $PKGBUILD_SIG_URL ;
-     for remote_file in ${REMOTE_FILES[@]}
+     for remote_file in ${REMOTE_FILENAMES[@]}
      do  if [ -f $remote_file -a "$(stat --printf='%s' $remote_file)" != "9" ] # 'Not Found'
          then TraceStep "downloaded $remote_file"
          else TraceStep "failed to download $remote_file"
-#               source ${HOOKS_DIR}/debug-remote-files.sh.inc
+#               source $(git config --local core.hooksPath)/debug-remote-files.sh.inc
               exit 1
          fi
      done
@@ -178,7 +194,7 @@ then (($IS_AMEND_COMMIT)) && exit 0
           diff $PKGBUILD_FILE.sig ./PKGBUILD.sig                                > /dev/null
      then TraceStep "verified remote tarball, PKGBUILD, and signatures"
      else TraceStep "failed to verify remote tarball, PKGBUILD, or signatures"
-#           source ${HOOKS_DIR}/debug-remote-files.sh.inc
+#           source $(git config --local core.hooksPath)/debug-remote-files.sh.inc
           exit 1
      fi
 
@@ -188,17 +204,64 @@ then (($IS_AMEND_COMMIT)) && exit 0
      # copy OBS files to local OSC build directory and trigger remote builds
      TraceStep "populating OSC build directory"
      cd $OSC_DIR/ && rm ./*
-     for obs_file in ${OBS_FILES[@]} ; do cp $obs_file $OSC_DIR/ ; done ;
-     osc commit
+     for obs_file in ${OBS_FILES[@]}
+     do  cp $obs_file $OSC_DIR/
+         osc add ./$(basename $obs_file) > /dev/null
+     done
+     TraceStep "triggering OSC remote builds"
+     osc checkin --message=$OSC_COMMIT_MSG > /dev/null
 
      # cleanup transient files
-     TraceStep "cleaning up"
-     transient_files=( $(for ea in ${CLEANUP_FILES[@]} ; do echo $ea ; done | sort | uniq) )
-     for transient_file in ${transient_files[@]} ; do rm $transient_file ; done ;
+     TraceStep "cleaning up transient files"
+     cd $PROJECT_DIR
+     for transient_file in ${CLEANUP_FILES[@]} ; do rm $transient_file ; done ;
+     git clean $GIT_CLEAN_OPTIONS &> /dev/null
 
 
      ### debian steps ###
 
-     # rename tarball for debain
+     # rename tarball and prepare working tree for debain
+     rm -rf ../${DEBIAN_NAME}*${VERSION}*
      mv $TARBALL_FILE ../$DEB_TARBALL_FILENAME
+     [ "$DEB_BUILD_TOOL" == 'gbp' -a ! -f debian/gbp.conf ] && cp $HOOKS_PATH/gbp.conf debian/
+
+     # build/validate debian package
+     TraceStep "building debian package with '$"$DEB_BUILD_TOOL"'"
+     case "$DEB_BUILD_TOOL" in
+     'debuild') debuild --unsigned-changes --unsigned-source
+                deb_file=$(ls ../${DEBIAN_NAME}_${VERSION}-*_${DEB_BUILD_ARCH}.deb 2> /dev/null)
+                sudo piuparts --save=$CHROOTBALL --basetgz=$CHROOTBALL              \
+                              --distribution=$DEB_BUILD_DIST --arch=$DEB_BUILD_ARCH \
+                              --mirror="$DEBOOTSTRAP_REPO" $deb_file
+                (($?)) && echo "piuparts failed for '$deb_file'" && exit 1
+     ;;
+     'sbuild') sudo sbuild-createchroot --make-sbuild-tarball=$CHROOTBALL $DEB_BUILD_DIST \
+                                        `mktemp --directory` "$DEBOOTSTRAP_REPO"
+               sbuild --dist=$DEB_BUILD_DIST --arch=$DEB_BUILD_ARCH          \
+                      --run-piuparts --piuparts-opts="--basetgz=$CHROOTBALL"
+     ;;
+     'gbp') DIST=$DEB_BUILD_DIST ARCH=$DEB_BUILD_ARCH git-pbuilder create --extrapackages 'eatmydata' &> $LOG_FILE
+            DIST=$DEB_BUILD_DIST ARCH=$DEB_BUILD_ARCH git-pbuilder update --extrapackages 'eatmydata' &> $LOG_FILE || true
+            [ ! -d $PIUPARTS_CHROOT ] && echo "could not create chroot '$PIUPARTS_CHROOT'" && exit 1
+
+            gbp buildpackage --git-dist=$DEB_BUILD_DIST --git-arch=$DEB_BUILD_ARCH              \
+                             --git-pbuilder --git-tag --git-retag --git-notify=off &> $LOG_FILE
+            deb_file=$(ls ../${DEBIAN_NAME}_${VERSION}-*_${DEB_BUILD_ARCH}.deb 2> /dev/null)
+            [ ! -f "$deb_file" ] && echo "package creation failed" && exit 1
+
+            TraceStep "testing debian package install/uninstall"
+            sudo piuparts --distribution=$DEB_BUILD_DIST --arch=$DEB_BUILD_ARCH     \
+                          --existing-chroot=$PIUPARTS_CHROOT $deb_file &> $LOG_FILE
+            (($?)) && echo "piuparts failed for '$deb_file'" && exit 1
+
+            debian_version=debian/$(dpkg-parsechangelog --show-field version)
+            debian_tag=$(git tag --points-at HEAD)
+            [ "$debian_version" != "$debian_tag" ] && TraceError "improper debian tag" && exit 1
+
+            TraceStep "pushing debian tag to github"
+            git push --force $REMOTE_NAME $debian_tag 2> /dev/null
+     ;;
+     esac
+
+     TraceStage "completed packaging-specific post-commit hooks"
 fi
